import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    habitTracker: 'Habit Tracker',
    budgetTracker: 'Budget Tracker',
    habitsDone: 'Habits Done',
    budgetLeft: 'Budget Left',
    yourHabits: 'Your Habits',
    habitName: 'Habit name',
    descriptionOptional: 'Description (optional)',
    category: 'Category',
    addHabit: '+ Add Habit',
    todaysProgress: "Today's Progress",
    completed: 'completed',
    toggleCompletion: 'Toggle completion',
    delete: 'Delete',
    loading: 'Loading...',
    yourBudget: 'Your Budget',
    amount: 'Amount',
    date: 'Date',
    type: 'Type',
    income: 'Income',
    expense: 'Expense',
    add: '+ Add',
    monthlyIncome: 'This month income:',
    monthlyExpenses: 'This month expenses:',
    balance: 'Balance:',
    deleteItem: 'Delete item',
    en: 'EN',
    ru: 'RU',
    themeLight: 'Light',
    themeDark: 'Dark',
    successAdd: 'Successfully added',
    successDelete: 'Successfully deleted',
    errorAdd: 'Failed to add',
    errorDelete: 'Failed to delete',
    errorLoad: 'Failed to load',
    invalidAmount: 'Please enter a valid positive amount',
    categoryRequired: 'Category is required',
    previousWeek: 'Previous week',
    nextWeek: 'Next week',
    today: 'Today',
    noCompletions: 'No completions',
    streak: 'Streak',
    dayStreak: 'day streak',
    daysStreak: 'days streak',
    frequency: 'Frequency',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    schedule: 'Schedule',
    selectDays: 'Select days',
    selectDaysOfMonth: 'Select days of month',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
    scheduledDay: 'Scheduled day',
    thisWeekProgress: 'This week',
    todayNotScheduled: 'Today is not a scheduled day',
    habitNameRequired: 'Habit name is required',
    scheduleRequired: 'Please select at least one day for scheduled habits',
    dailyNote: 'Daily Note',
    notePlaceholder: 'Write your note for this day...',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    saving: 'Saving...',
    deleteNoteConfirm: 'Delete this note?',
    errorSaveNote: 'Failed to save note',
    errorDeleteNote: 'Failed to delete note',
    addNote: 'Add note',
    budgetPlan: 'Budget Plan',
    planned: 'Planned',
    actual: 'Actual',
    comparison: 'Comparison',
    plannedAmount: 'Planned Amount',
    difference: 'Difference',
    categoryBreakdown: 'Category Breakdown',
    selectMonth: 'Select Month/Year',
    noPlans: 'No plans yet. Add your first plan above.',
    deletePlanConfirm: 'Delete this plan?',
    allFieldsRequired: 'All fields are required',
    sleepTracking: 'Sleep Tracking',
    sleepHours: 'Sleep Hours',
    sleep: 'Sleep',
    addSleep: 'Add sleep',
    hoursSlept: 'Hours Slept',
    hours: 'hours',
    sleepRecommendation: 'Recommended: 7-9 hours',
    invalidSleepHours: 'Please enter a valid number between 0 and 24',
    errorSaveSleep: 'Failed to save sleep data',
    errorDeleteSleep: 'Failed to delete sleep data',
    deleteSleepConfirm: 'Delete sleep data for this day?',
    goodSleep: 'Good (7-9h)',
    insufficient: '<7h',
    averageSleep: 'Average',
    insufficientDays: 'Insufficient Days',
    noData: 'No data',
    home: 'Home',
    today: 'Today',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    calendar: 'Calendar',
    addEvent: 'Add Event',
    newEvent: 'New Event',
    editEvent: 'Edit Event',
    eventTitleRequired: 'Event title is required',
    eventTitlePlaceholder: 'Event title',
    eventDescriptionPlaceholder: 'Add description...',
    errorSaveEvent: 'Failed to save event',
    errorDeleteEvent: 'Failed to delete event',
    deleteEventConfirm: 'Delete this event?',
    startDate: 'Start Date',
    endDate: 'End Date',
    startTime: 'Start Time',
    endTime: 'End Time',
    allDay: 'All Day',
    color: 'Color',
    more: 'more',
    editNote: 'Edit Note',
    addNote: 'Add Note',
    dailyNote: 'Daily Note',
    calendarNote: 'Calendar Note',
    habitNote: 'Habit Note',
    notePlaceholder: 'Write your note...',
    noteTitlePlaceholder: 'Note title (optional)',
    content: 'Content',
    taskTracker: 'Task Tracker',
    workTaskTracker: 'Work Task Tracker',
    addTask: 'Add Task',
    createTask: 'Create Task',
    editTask: 'Edit Task',
    taskTitleRequired: 'Task title is required',
    taskTitlePlaceholder: 'Enter task title',
    taskDescriptionPlaceholder: 'Enter task description',
    dueDate: 'Due Date',
    priority: 'Priority',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
    status: 'Status',
    todo: 'To Do',
    inProgress: 'In Progress',
    done: 'Done',
    subtasks: 'Subtasks',
    subtaskTitlePlaceholder: 'Subtask title',
    addSubtaskPlaceholder: 'Add subtask...',
    attachments: 'Attachments',
    uploadFile: 'Upload File',
    notes: 'Notes',
    addNotePlaceholder: 'Add a note...',
    allStatuses: 'All Statuses',
    allPriorities: 'All Priorities',
    sortByDueDate: 'Sort by Due Date',
    sortByPriority: 'Sort by Priority',
    sortByCreated: 'Sort by Created',
    noTasks: 'No tasks in this category',
    deleteTaskConfirm: 'Delete this task?',
    errorSaveTask: 'Failed to save task',
    errorDeleteTask: 'Failed to delete task',
    errorUploadFile: 'Failed to upload file',
    errorDeleteAttachment: 'Failed to delete attachment',
    errorAddNote: 'Failed to add note',
    errorDeleteNote: 'Failed to delete note',
    edit: 'Edit',
    title: 'Title',
    description: 'Description',
  },
  ru: {
    habitTracker: 'Трекер привычек',
    budgetTracker: 'Бюджет',
    habitsDone: 'Привычек выполнено',
    budgetLeft: 'Остаток бюджета',
    yourHabits: 'Ваши привычки',
    habitName: 'Название привычки',
    descriptionOptional: 'Описание (необязательно)',
    category: 'Категория',
    addHabit: '+ Добавить привычку',
    todaysProgress: 'Прогресс за сегодня',
    completed: 'выполнено',
    toggleCompletion: 'Переключить выполнение',
    delete: 'Удалить',
    loading: 'Загрузка...',
    yourBudget: 'Ваш бюджет',
    amount: 'Сумма',
    date: 'Дата',
    type: 'Тип',
    income: 'Доход',
    expense: 'Расход',
    add: '+ Добавить',
    monthlyIncome: 'Доход за месяц:',
    monthlyExpenses: 'Расходы за месяц:',
    balance: 'Баланс:',
    deleteItem: 'Удалить запись',
    en: 'EN',
    ru: 'RU',
    themeLight: 'Светлая',
    themeDark: 'Тёмная',
    successAdd: 'Успешно добавлено',
    successDelete: 'Успешно удалено',
    errorAdd: 'Не удалось добавить',
    errorDelete: 'Не удалось удалить',
    errorLoad: 'Не удалось загрузить',
    invalidAmount: 'Введите положительное число',
    categoryRequired: 'Категория обязательна',
    previousWeek: 'Предыдущая неделя',
    nextWeek: 'Следующая неделя',
    today: 'Сегодня',
    noCompletions: 'Нет выполненных',
    streak: 'Серия',
    dayStreak: 'день подряд',
    daysStreak: 'дней подряд',
    frequency: 'Частота',
    daily: 'Ежедневно',
    weekly: 'Еженедельно',
    monthly: 'Ежемесячно',
    schedule: 'Расписание',
    selectDays: 'Выберите дни',
    selectDaysOfMonth: 'Выберите дни месяца',
    mon: 'Пн',
    tue: 'Вт',
    wed: 'Ср',
    thu: 'Чт',
    fri: 'Пт',
    sat: 'Сб',
    sun: 'Вс',
    scheduledDay: 'Запланированный день',
    thisWeekProgress: 'Эта неделя',
    todayNotScheduled: 'Сегодня не запланированный день',
    habitNameRequired: 'Название привычки обязательно',
    scheduleRequired: 'Пожалуйста, выберите хотя бы один день для запланированных привычек',
    dailyNote: 'Ежедневная заметка',
    notePlaceholder: 'Напишите заметку на этот день...',
    save: 'Сохранить',
    cancel: 'Отмена',
    close: 'Закрыть',
    saving: 'Сохранение...',
    deleteNoteConfirm: 'Удалить эту заметку?',
    errorSaveNote: 'Не удалось сохранить заметку',
    errorDeleteNote: 'Не удалось удалить заметку',
    addNote: 'Добавить заметку',
    budgetPlan: 'План бюджета',
    planned: 'Запланировано',
    actual: 'Фактически',
    comparison: 'Сравнение',
    plannedAmount: 'Запланированная сумма',
    difference: 'Разница',
    categoryBreakdown: 'Разбивка по категориям',
    selectMonth: 'Выберите месяц/год',
    noPlans: 'Планов пока нет. Добавьте первый план выше.',
    deletePlanConfirm: 'Удалить этот план?',
    allFieldsRequired: 'Все поля обязательны',
    sleepTracking: 'Отслеживание сна',
    sleepHours: 'Часы сна',
    sleep: 'Сон',
    addSleep: 'Добавить сон',
    hoursSlept: 'Часов спал',
    hours: 'часов',
    sleepRecommendation: 'Рекомендуется: 7-9 часов',
    invalidSleepHours: 'Пожалуйста, введите число от 0 до 24',
    errorSaveSleep: 'Не удалось сохранить данные о сне',
    errorDeleteSleep: 'Не удалось удалить данные о сне',
    deleteSleepConfirm: 'Удалить данные о сне за этот день?',
    goodSleep: 'Хорошо (7-9ч)',
    insufficient: '<7ч',
    averageSleep: 'Среднее',
    insufficientDays: 'Недостаточные дни',
    noData: 'Нет данных',
    home: 'Главная',
    today: 'Сегодня',
    previousMonth: 'Предыдущий месяц',
    nextMonth: 'Следующий месяц',
    calendar: 'Календарь',
    addEvent: 'Добавить событие',
    newEvent: 'Новое событие',
    editEvent: 'Редактировать событие',
    eventTitleRequired: 'Название события обязательно',
    eventTitlePlaceholder: 'Название события',
    eventDescriptionPlaceholder: 'Добавить описание...',
    errorSaveEvent: 'Не удалось сохранить событие',
    errorDeleteEvent: 'Не удалось удалить событие',
    deleteEventConfirm: 'Удалить это событие?',
    startDate: 'Дата начала',
    endDate: 'Дата окончания',
    startTime: 'Время начала',
    endTime: 'Время окончания',
    allDay: 'Весь день',
    color: 'Цвет',
    more: 'еще',
    editNote: 'Редактировать заметку',
    addNote: 'Добавить заметку',
    dailyNote: 'Ежедневная заметка',
    calendarNote: 'Заметка календаря',
    habitNote: 'Заметка привычки',
    notePlaceholder: 'Напишите заметку...',
    noteTitlePlaceholder: 'Название заметки (необязательно)',
    content: 'Содержание',
    taskTracker: 'Трекер задач',
    workTaskTracker: 'Рабочий трекер задач',
    addTask: 'Добавить задачу',
    createTask: 'Создать задачу',
    editTask: 'Редактировать задачу',
    taskTitleRequired: 'Название задачи обязательно',
    taskTitlePlaceholder: 'Введите название задачи',
    taskDescriptionPlaceholder: 'Введите описание задачи',
    dueDate: 'Срок выполнения',
    priority: 'Приоритет',
    low: 'Низкий',
    medium: 'Средний',
    high: 'Высокий',
    urgent: 'Срочный',
    status: 'Статус',
    todo: 'К выполнению',
    inProgress: 'В процессе',
    done: 'Выполнено',
    subtasks: 'Подзадачи',
    subtaskTitlePlaceholder: 'Название подзадачи',
    addSubtaskPlaceholder: 'Добавить подзадачу...',
    attachments: 'Вложения',
    uploadFile: 'Загрузить файл',
    notes: 'Заметки',
    addNotePlaceholder: 'Добавить заметку...',
    allStatuses: 'Все статусы',
    allPriorities: 'Все приоритеты',
    sortByDueDate: 'Сортировать по сроку',
    sortByPriority: 'Сортировать по приоритету',
    sortByCreated: 'Сортировать по дате создания',
    noTasks: 'Нет задач в этой категории',
    deleteTaskConfirm: 'Удалить эту задачу?',
    errorSaveTask: 'Не удалось сохранить задачу',
    errorDeleteTask: 'Не удалось удалить задачу',
    errorUploadFile: 'Не удалось загрузить файл',
    errorDeleteAttachment: 'Не удалось удалить вложение',
    errorAddNote: 'Не удалось добавить заметку',
    errorDeleteNote: 'Не удалось удалить заметку',
    edit: 'Редактировать',
    title: 'Название',
    description: 'Описание',
  },
};

const LanguageContext = createContext({ language: 'en', setLanguage: () => {}, t: (k) => k, daysShort: [], habitCategories: [], budgetCategories: [] });

export function LanguageProvider({ children }) {
  const getDefault = () => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('lang') : null;
    if (saved && (saved === 'en' || saved === 'ru')) return saved;
    const nav = typeof navigator !== 'undefined' ? (navigator.language || navigator.userLanguage || 'en') : 'en';
    return nav.startsWith('ru') ? 'ru' : 'en';
  };

  const [language, setLanguageState] = useState(getDefault);

  useEffect(() => {
    try { localStorage.setItem('lang', language); } catch {}
  }, [language]);

  const setLanguage = (lang) => {
    if (lang === 'en' || lang === 'ru') setLanguageState(lang);
  };

  const t = useMemo(() => {
    const dict = translations[language] || translations.en;
    return (key) => dict[key] || key;
  }, [language]);

  const daysShort = useMemo(() => (
    language === 'ru' ? ['Пн','Вт','Ср','Чт','Пт','Сб','Вс'] : ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
  ), [language]);

  const defaultHabit = ['Health','Work','Personal Dev','Fun'];
  const defaultHabitRu = ['Здоровье','Работа','Саморазвитие','Отдых'];
  const defaultBudget = ['Food','Transport','Entertainment','Bills','Shopping'];
  const defaultBudgetRu = ['Еда','Транспорт','Развлечения','Счета','Покупки'];

  const habitCategories = useMemo(() => (
    language === 'ru' ? defaultHabitRu : defaultHabit
  ), [language]);
  const budgetCategories = useMemo(() => (
    language === 'ru' ? defaultBudgetRu : defaultBudget
  ), [language]);

  const value = useMemo(() => ({ language, setLanguage, t, daysShort, habitCategories, budgetCategories }), [language, t, daysShort, habitCategories, budgetCategories]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}


